
server:
  port: 8090
  servlet:
    context-path: /approve-client-adapter

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  devtools:
    livereload:
      enabled: false
  http:
    log-request-details: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      show-details: always

info:
  contact:
    email: xingjiajun88@sina.com

hx:
  nc:
    IP: http://114.113.234.244:8091
    host: http://114.113.234.244:8095
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://114.118.6.18:9090
    register-code: 3012
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: D:\lpd.json

---
spring:
  profiles: hx64

hx:
  nc:
    IP: http://172.17.10.64:8081
    host: http://114.113.234.244:8095
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://114.118.6.18:9090
    register-code: 3012
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: /usr/local/project/lpd.json

logging:
  path: /usr/local/project/
  file: approve-client-adapter.log
  level:
    root: info

---
spring:
  profiles: prod

hx:
  nc:
    IP: http://172.17.10.64:8081
    host: http://172.17.10.64:${server.port}
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://114.118.6.18:9090
    register-code: 3011
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: /usr/local/project/lpd.json

logging:
  path: /usr/local/project/
  file: approve-client-adapter.log
  level:
    root: warn
