#tomcat
server:
  port: 8090
  servlet.context-path: /approve-client-adapter

#spring
spring:
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart.trigger-file: .trigger
    livereload.enabled: false
  datasource:
    url: jdbc:h2:D:/h2/h2db
    username: aca
    password: aca
  h2.console:
      enabled: true
      settings.web-allow-others: true
  jpa.hibernate.ddl-auto: update
  http.encoding.force: true
  task:
    execution.pool:
      max-size: 16
      queue-capacity: 100
    scheduling.pool.size: 6


#  data.jpa.repositories.bootstrap-mode: lazy

#actuator
management:
  endpoints.web.exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint.health.show-details: always
info.contact.email: xingjiajun88@sina.com

#app
hx.nc:
  IP: http://172.17.10.64:8081
#  IP: http://172.17.10.65:8081
  host: http://114.113.234.244:8095
  userid: zxyadmin
  groupid: 0001V610000000000EEN
  oa-IP: http://101.254.234.187
  register-code: 3012
  oa-user: ncrest
  oa-pwd: a1234567
  file-path: D:\lpd.json
  nc65ph-Group-Id: 0001A1100000000029SK
  nc65ph-IP: http://172.20.102.54:9998
  nc65ph-Register-Code: 3013
  nc65ds-Group-Id: 0001T1100000000003JS
  nc65ds-IP: http://172.20.8.39
  nc65ds-Register-Code: 3014

---
spring.profiles: hx64

spring:
  datasource.url: jdbc:h2:/usr/local/project/h2/h2db

hx.nc:
    IP: http://172.17.10.64:8081
    host: http://114.113.234.244:8095
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://101.254.234.187
    register-code: 3012
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: /usr/local/project/lpd.json
    nc65ph-Group-Id: 0001A1100000000029SK
    nc65ph-IP: http://172.20.102.54:9998
    nc65ph-Register-Code: 3013
    nc65ds-Group-Id: 0001T1100000000003JS
    nc65ds-IP: http://172.20.8.39
    nc65ds-Register-Code: 3014

logging:
  path: /usr/local/project/
  file: approve-client-adapter.log
  level.root: info

---
spring.profiles: prod

spring:
  datasource:
    url: jdbc:mysql://rm-2zely9zmlbl3rmcr7zo.mysql.rds.aliyuncs.com/hxaca
    driver-class-name: com.mysql.jdbc.Driver

hx.nc:
    IP: http://172.17.10.65:8081
#    host: http://114.113.234.242:9095
    host: http://101.254.191.78:8090
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://oa.hxgp.com
    register-code: 3012
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: /usr/local/project/lpd.json
    nc65ph-Group-Id: 0001A1100000000029SK
    nc65ph-IP: http://172.20.102.53:8082
    nc65ph-Register-Code: 3013
    nc65ds-Group-Id: 0001A110000000000BLA
    nc65ds-IP: http://172.20.10.241
    nc65ds-Register-Code: 3014

logging:
  path: /usr/local/project/
  file: approve-client-adapter.log
  level.root: info
