#tomcat
server:
  port: 8090
  servlet.context-path: /approve-client-adapter

#spring
spring:
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart.trigger-file: .trigger
    livereload.enabled: false
  datasource:
    url: jdbc:h2:D:/h2/h2db
    username: aca
    password: aca
  h2.console.enabled: true
  jpa.hibernate.ddl-auto: update
#  data.jpa.repositories.bootstrap-mode: lazy

#actuator
management:
  endpoints.web.exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint.health.show-details: always
info.contact.email: xingjiajun88@sina.com

#app
hx.nc:
    IP: http://114.113.234.244:8091
    host: http://114.113.234.244:8095
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://114.118.6.18:9090
    register-code: 3012
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: D:\lpd.json

---
spring.profiles: hx64

spring:
  datasource.url: jdbc:h2:/usr/local/project/h2/h2db

hx.nc:
    IP: http://172.17.10.64:8081
    host: http://114.113.234.244:8095
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://114.118.6.18:9090
    register-code: 3012
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: /usr/local/project/lpd.json

logging:
  path: /usr/local/project/
  file: approve-client-adapter.log
  level.root: info

---
spring.profiles: prod

spring:
  datasource.url: jdbc:h2:/usr/local/project/h2/h2db

hx.nc:
    IP: http://172.17.10.64:8081
    host: http://172.17.10.64:${server.port}
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://114.118.6.18:9090
    register-code: 3011
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: /usr/local/project/lpd.json

logging:
  path: /usr/local/project/
  file: approve-client-adapter.log
  level.root: warn
