
server:
#  port: 8090
  servlet:
    context-path: /approve-client-adapter

spring:
  profiles:
    active: prod
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


#  mvc:
#    servlet:
#      path: /approve-client-adapter
#  devtools:
#    livereload:
#      enabled: false

---
spring:
  profiles: dev

hx:
  nc:
    IP: http://172.20.54.250:8086
    host: http://172.20.54.250:8086
    userid: zxyadmin
    groupid: 0001A9100000000006H5
    oa-IP: http://172.25.10.53
    register-code: 3011
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: D:\lpd.json

---
spring:
  profiles: prod

hx:
  nc:
    IP: http://172.17.10.64:8081
    userid: zxyadmin
    groupid: 0001V610000000000EEN
    oa-IP: http://172.25.10.53
    register-code: 3011
    oa-user: ncrest
    oa-pwd: a1234567
    file-path: D:\lpd.json
#    file-path: /usr/local/project/lpd.json

#logging:
#  path: /logs/
#  file: approve-client-adapter.log
#  level: warn
